### ISSUE TITLE
Remove all Billmate payment methods for new back-end orders

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/magento#37] opened 2015-01-19 09:56 UTC

**Comment by Boxedsolutions** [comment] 2015-01-19 13:58
Should be fixed

**Comment by andyjohansson** [comment] 2015-01-20 21:01
Can you verify @joakim-combain ?

**Comment by joakim-combain** [comment] 2015-01-21 08:20
Can you clarify what the issue is? I don't understand what it is that I should verify.

**Comment by Boxedsolutions** [comment] 2015-01-21 08:21
If you go in the backend and tries to add a order manually. Our Payment methods shouldnt be visible.

**Comment by andyjohansson** [comment] 2015-01-21 08:37
We will add them back once we have the support for this.

**Comment by joakim-combain** [comment] 2015-01-21 11:25
This is fixed.

**Closed** 2015-01-21 13:19 UTC
Labels: bug
